name: project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas
      - openpyxl
      - ipykernel
      - notebook
      - jupyterlab
      - altair
      - mysql-connector-python
      - streamlit
      - matplotlib
      - scikit-learn
      - autopep8
      - appnope @ file:///home/conda/feedstock_root/build_artifacts/appnope_1649077682618/work
      - asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work
      - attrs @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/attrs_1699281960663/work
      -	Bottleneck @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/bottleneck_1699237772214/work
      -	comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1691044910542/work
      -	contourpy @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/contourpy_1701814001737/work
      -	cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
      -	Cython==3.0.7
      -	debugpy @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/debugpy_1699253073094/work
      -	decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
      -	exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1700579780973/work
      -	executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1698579936712/work
      -	fastjsonschema @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/python-fastjsonschema_1699238535414/work
      -	fonttools==4.25.0
      -	importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1703269254275/work
      -	ipykernel @ file:///Users/runner/miniforge3/conda-bld/ipykernel_1703631823913/work
      -	ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1703263236586/work
      -	jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1696326070614/work
      -	joblib @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/joblib_1699241239748/work
      -	jsonschema @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/jsonschema_1701803145350/work
      -	jsonschema-specifications @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/jsonschema-specifications_1701803122948/work
      -	jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1699283905679/work
      -	jupyter_core @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/jupyter_core_1701803168398/work
      -	kiwisolver @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/kiwisolver_1699239145780/work
      -	lightgbm @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/lightgbm_1701815620962/work
      -	matplotlib @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/matplotlib-suite_1699241272749/work
      -	matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
      -	munkres==1.1.4
      -	nbformat @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/nbformat_1701803214283/work
      -	nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1697083700168/work
      -	numexpr @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/numexpr_1699237935415/work
      -	numpy @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_c0s16d4ba1/croot/numpy_and_numpy_base_1701295077539/work/dist/numpy-1.26.2-cp312-cp312-macosx_11_0_arm64.whl#sha256=3ef98b52001fc0e2266d3454005c31e553aa633ec4aaf3ac3aef67a63e51e807
      -	packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1696202382185/work
      -	pandas @ file:///private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_82r7p4atwy/croot/pandas_1702318000240/work/dist/pandas-2.1.4-cp312-cp312-macosx_11_0_arm64.whl#sha256=142530670b1e4125a2466ecf7521689e9e72ac90d1e53a96b5ce39180a797870
      -	parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
      -	patsy==0.5.3
      -	pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
      -	pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
      -	Pillow @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/pillow_1699239265580/work
      -	platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1701708255999/work
      -	plotly @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/plotly_1699242638798/work
      -	pmdarima==2.0.4
      -	prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1702399386289/work
      -	psutil @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/psutil_1699248249804/work
      -	ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
      -	pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
      -	Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1700607939962/work
      -	pyparsing @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/pyparsing_1699239441347/work
      -	python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
      -	pytz @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/pytz_1699238107851/work
      -	pyzmq @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/pyzmq_1699262382926/work
      -	referencing @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/referencing_1701803099840/work
      -	rpds-py @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/rpds-py_1699262599461/work
      -	scikit-learn @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/scikit-learn_1699243168502/work
      -	scipy @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/scipy_1701809213817/work/dist/scipy-1.11.4-cp312-cp312-macosx_11_0_arm64.whl#sha256=a3cbe006dde303d7cb9500d1b395f4327160814d8a359203b19094bdf6b5df9a
      -	seaborn==0.13.0
      -	setuptools==68.2.2
      -	six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
      -	stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
      -	statsmodels @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/statsmodels_1701807246681/work
      -	tenacity @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/tenacity_1699241689752/work
      -	threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work
      -	tornado @ file:///Users/builder/cbouss/perseverance-python-buildout/croot/tornado_1699243541634/work
      -	traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1701095650114/work
      -	typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1702176139754/work
      -	tzdata @ file:///croot/python-tzdata_1690578112552/work
      -	urllib3==2.1.0
      -	wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1700607916581/work
      -	wheel==0.41.2
      -	xgboost==1.7.3
      -	yellowbrick==1.5
      -	zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1695255097490/work

